"""
authority/categories.py — Operational Authority categories and weights.

A closed enum of the six authority categories an incoming data element can
carry, each with a fixed weight in [0, 1]. Weight expresses how much the
category contributes to a Decision Card's operational authority — higher =
closer to operational truth.

The weights are intentionally simple and transparent (NOT ML confidence):
directly observed data outweighs confirmed-system, which outweighs published,
which outweighs Horizon-predicted, which outweighs assumed/simulated.
"""

from __future__ import annotations

from enum import Enum
from types import MappingProxyType


class AuthorityCategory(Enum):
    """Operational Authority category for a single data element."""

    LIVE_OBSERVED = "LIVE_OBSERVED"            # directly observed operational data (AIS vessel position/static)
    LIVE_ENVIRONMENTAL = "LIVE_ENVIRONMENTAL"  # directly observed environmental data (weather, tides)
    CONFIRMED_SYSTEM = "CONFIRMED_SYSTEM"      # authenticated system-of-record integration
    CONFIRMED_PUBLISHED = "CONFIRMED_PUBLISHED"  # published operational info (no API contract)
    PREDICTED = "PREDICTED"                    # generated by Horizon (ETA, UKC, clearance, probability)
    ASSUMED = "ASSUMED"                        # fallback / simulated / placeholder

    @property
    def weight(self) -> float:
        """Fixed authority weight in [0, 1]."""
        return _WEIGHTS[self]


# Frozen weight table (MappingProxyType → no global mutable state).
_WEIGHTS = MappingProxyType({
    AuthorityCategory.LIVE_OBSERVED:       1.00,
    AuthorityCategory.LIVE_ENVIRONMENTAL:  1.00,
    AuthorityCategory.CONFIRMED_SYSTEM:    0.90,
    AuthorityCategory.CONFIRMED_PUBLISHED: 0.70,
    AuthorityCategory.PREDICTED:           0.50,
    AuthorityCategory.ASSUMED:             0.20,
})


def all_categories() -> tuple[AuthorityCategory, ...]:
    """Return every category, highest-weight first (stable ordering)."""
    return tuple(sorted(AuthorityCategory, key=lambda c: c.weight, reverse=True))
